/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author yujia1986
 */
public class pnl_hadoop_server extends javax.swing.JPanel {

    /**
     * Creates new form pnl_hadoop_server
     */
    public pnl_hadoop_server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_back = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txt_command = new javax.swing.JTextArea();
        Btn_Stop = new javax.swing.JButton();
        Btn_Start = new javax.swing.JButton();

        Txt_command.setEditable(false);
        Txt_command.setColumns(20);
        Txt_command.setRows(5);
        jScrollPane1.setViewportView(Txt_command);

        Btn_Stop.setText("Stop");
        Btn_Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_StopActionPerformed(evt);
            }
        });

        Btn_Start.setText("Start");
        Btn_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_StartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_backLayout = new javax.swing.GroupLayout(Pnl_back);
        Pnl_back.setLayout(Pnl_backLayout);
        Pnl_backLayout.setHorizontalGroup(
            Pnl_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_Start)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Stop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        Pnl_backLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Btn_Start, Btn_Stop});

        Pnl_backLayout.setVerticalGroup(
            Pnl_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_backLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Start)
                    .addComponent(Btn_Stop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_StartActionPerformed

        runhadoop runabletask = new runhadoop(0);
        new Thread(runabletask).start();
    }//GEN-LAST:event_Btn_StartActionPerformed

    private void Btn_StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_StopActionPerformed
        // TODO add your handling code here:
        runhadoop runabletask = new runhadoop(1);
        new Thread(runabletask).start();
    }//GEN-LAST:event_Btn_StopActionPerformed

    public class runhadoop implements Runnable {

        private final Integer Start_or_Stop;

        public runhadoop(Integer Start_or_Stop) {
            this.Start_or_Stop = Start_or_Stop;
        }

        public void run_hadoop(Integer Start_or_Stop) {
            Btn_Stop.setEnabled(false);
            Btn_Start.setEnabled(false);
            Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
            Pnl_back.setCursor(hourglassCursor);
            try {
            // TODO add your handling code here:
                String cmd = "";
                if (Start_or_Stop == 0) {
                    cmd = "start-all.sh";
                } else {
                    cmd = "stop-all.sh";
                }

                Process pr = Runtime.getRuntime().exec(cmd);
                BufferedReader in = new BufferedReader(new InputStreamReader(pr.getInputStream()));
                String line;
                while ((line = in.readLine()) != null) {
                    Txt_command.setText(Txt_command.getText() + line + "\n");
                }
                in.close();
                try {
                    pr.waitFor();
                } catch (InterruptedException ex) {
                    Logger.getLogger(pnl_hadoop_server.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (IOException ex) {
                Logger.getLogger(pnl_hadoop_server.class.getName()).log(Level.SEVERE, null, ex);
            }
            Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
            Pnl_back.setCursor(normalCursor);
            Btn_Stop.setEnabled(true);
            Btn_Start.setEnabled(true);
        }

        @Override
        public void run() {
            run_hadoop(Start_or_Stop);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Start;
    private javax.swing.JButton Btn_Stop;
    private javax.swing.JPanel Pnl_back;
    private javax.swing.JTextArea Txt_command;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
