/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import importToNewTable.createDataJob;
import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author yujia1986
 */
public class pnl_hbase_server extends javax.swing.JPanel {

    /**
     * Creates new form pnl_hbase_server
     */
    public pnl_hbase_server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_back = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txt_command = new javax.swing.JTextArea();
        Btn_Stop = new javax.swing.JButton();
        Btn_Start = new javax.swing.JButton();
        lbl_hbase_server = new javax.swing.JLabel();
        txt_hbase_server = new javax.swing.JTextField();
        txt_zookeeper_port = new javax.swing.JTextField();
        lbl_zookeeper_port = new javax.swing.JLabel();
        txt_hbase_port = new javax.swing.JTextField();
        lbl_port = new javax.swing.JLabel();

        Txt_command.setEditable(false);
        Txt_command.setColumns(20);
        Txt_command.setRows(5);
        jScrollPane1.setViewportView(Txt_command);

        Btn_Stop.setText("Stop");
        Btn_Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_StopActionPerformed(evt);
            }
        });

        Btn_Start.setText("Start");
        Btn_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_StartActionPerformed(evt);
            }
        });

        lbl_hbase_server.setText("HBase Server");

        lbl_zookeeper_port.setText("Zookeeper Port");

        lbl_port.setText("Port");

        javax.swing.GroupLayout Pnl_backLayout = new javax.swing.GroupLayout(Pnl_back);
        Pnl_back.setLayout(Pnl_backLayout);
        Pnl_backLayout.setHorizontalGroup(
            Pnl_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
            .addGroup(Pnl_backLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_backLayout.createSequentialGroup()
                        .addComponent(Btn_Start)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Stop)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Pnl_backLayout.createSequentialGroup()
                        .addComponent(lbl_hbase_server)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_hbase_server)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_port)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_hbase_port, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_zookeeper_port)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_zookeeper_port, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        Pnl_backLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Btn_Start, Btn_Stop});

        Pnl_backLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_hbase_port, txt_zookeeper_port});

        Pnl_backLayout.setVerticalGroup(
            Pnl_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_backLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hbase_server)
                    .addComponent(txt_hbase_server, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_zookeeper_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_zookeeper_port)
                    .addComponent(txt_hbase_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_port))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Start)
                    .addComponent(Btn_Stop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
        );

        Pnl_backLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbl_hbase_server, lbl_port, lbl_zookeeper_port, txt_hbase_port, txt_hbase_server, txt_zookeeper_port});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_StartActionPerformed

        try {
            saveServerInfo();
            runhbase runabletask = new runhbase(0);
            new Thread(runabletask).start();
        } catch (IOException ex) {
            Logger.getLogger(pnl_hbase_server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_StartActionPerformed

    private void Btn_StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_StopActionPerformed
        // TODO add your handling code here:
        runhbase runabletask = new runhbase(1);
        new Thread(runabletask).start();
    }//GEN-LAST:event_Btn_StopActionPerformed

    public class runhbase implements Runnable {

        private Integer Start_or_Stop;

        public runhbase(Integer Start_or_Stop) {
            this.Start_or_Stop = Start_or_Stop;
        }

        public void run_hbase(Integer Start_or_Stop) {
            Btn_Stop.setEnabled(false);
            Btn_Start.setEnabled(false);
            Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
            Pnl_back.setCursor(hourglassCursor);
            try {
                // TODO add your handling code here:
                String cmd = "";
                if (Start_or_Stop == 0) {
                    cmd = "start-hbase.sh";
                } else {
                    cmd = "stop-hbase.sh";
                }

                Process pr = Runtime.getRuntime().exec(cmd);
                BufferedReader in = new BufferedReader(new InputStreamReader(pr.getInputStream()));
                String line;
                while ((line = in.readLine()) != null) {
                    Txt_command.setText(Txt_command.getText() + line + "\n");
                }
                in.close();
                try {
                    pr.waitFor();
                } catch (InterruptedException ex) {
                    Logger.getLogger(pnl_hbase_server.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (IOException ex) {
                Logger.getLogger(pnl_hbase_server.class.getName()).log(Level.SEVERE, null, ex);
            }
            Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
            Pnl_back.setCursor(normalCursor);
            Btn_Stop.setEnabled(true);
            Btn_Start.setEnabled(true);
        }

        @Override
        public void run() {
            run_hbase(Start_or_Stop);
        }

    }

    public void saveServerInfo() throws IOException {
        String[] serverInfo = new String[3];
        serverInfo[0] = txt_hbase_server.getText();
        serverInfo[1] = txt_hbase_port.getText();
        serverInfo[2] = txt_zookeeper_port.getText();
        importToNewTable.createDataJob pathClear = new createDataJob();
        File path = new File("/tmp/HVCF/hbaseServerInfo");
        pathClear.deleteDir(path);
        path.mkdirs();
        File f = new File("/tmp/HVCF/hbaseServerInfo/hbaseServerInfo.txt");
        try (FileWriter out = new FileWriter(f)) {
            out.write(serverInfo[0]+","+serverInfo[1]+","+serverInfo[2]);
            out.close();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Start;
    private javax.swing.JButton Btn_Stop;
    private javax.swing.JPanel Pnl_back;
    private javax.swing.JTextArea Txt_command;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_hbase_server;
    private javax.swing.JLabel lbl_port;
    private javax.swing.JLabel lbl_zookeeper_port;
    private javax.swing.JTextField txt_hbase_port;
    private javax.swing.JTextField txt_hbase_server;
    private javax.swing.JTextField txt_zookeeper_port;
    // End of variables declaration//GEN-END:variables
}
